# Generated by Django 6.0.6 on 2026-06-17 04:44

import decks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='first_pages/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('year', models.PositiveIntegerField(default=decks.models.current_year)),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=decks.models.current_month)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'first page',
                'verbose_name_plural': 'first pages',
                'ordering': ['-created_at'],
            },
        ),
    ]
