# Generated by Django 6.0.6 on 2026-06-17 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Key Metrics & Outcomes', max_length=200)),
                ('description', models.CharField(default='Coding - Overall', max_length=200)),
                ('score_title', models.CharField(default='Quality Score', max_length=100)),
                ('score_value', models.CharField(default='97.4%', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'next page',
                'verbose_name_plural': 'next pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NextPageCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='decks.nextpage')),
            ],
            options={
                'verbose_name': 'next page card',
                'verbose_name_plural': 'next page cards',
                'ordering': ['order'],
            },
        ),
    ]
