# Generated by Django 6.0.6 on 2026-06-17 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_nextpage_nextpagecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Client Additions', max_length=200)),
                ('content', models.TextField(default='New clients, strong partnerships, and a pipeline that keeps moving forward.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'agency page',
                'verbose_name_plural': 'agency pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgencyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencies', to='decks.agencypage')),
            ],
            options={
                'verbose_name': 'agency name',
                'verbose_name_plural': 'agency names',
                'ordering': ['order'],
            },
        ),
    ]
