# Generated by Django 6.0.6 on 2026-06-17 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_agencypage_agencyname'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'bullet card',
                'verbose_name_plural': 'bullet cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BulletPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Key Metrics & Outcomes', max_length=200)),
                ('description', models.CharField(default='RCM', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'bullet page',
                'verbose_name_plural': 'bullet pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulletItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='decks.bulletcard')),
            ],
            options={
                'verbose_name': 'bullet item',
                'verbose_name_plural': 'bullet items',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='bulletcard',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='decks.bulletpage'),
        ),
    ]
