# Generated by Django 6.0.6 on 2026-06-17 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0004_bulletcard_bulletpage_bulletitem_bulletcard_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDatePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Client Additions', max_length=200)),
                ('content', models.TextField(default='New clients, strong partnerships, and a pipeline that keeps moving forward.')),
                ('description', models.CharField(default='RCM', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'client date page',
                'verbose_name_plural': 'client date pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientDateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('went_live_on', models.DateField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='decks.clientdatepage')),
            ],
            options={
                'verbose_name': 'client date item',
                'verbose_name_plural': 'client date items',
                'ordering': ['order'],
            },
        ),
    ]
