# Generated by Django 6.0.6 on 2026-06-17 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0005_clientdatepage_clientdateitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSaysPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='What Our Clients Say...', max_length=200)),
                ('client_description', models.TextField()),
                ('client_name', models.CharField(help_text='Client or agency name shown under the quote.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'client says page',
                'verbose_name_plural': 'client says pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientSaysPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='client_says/')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='decks.clientsayspage')),
            ],
            options={
                'verbose_name': 'client says person',
                'verbose_name_plural': 'client says people',
                'ordering': ['order'],
            },
        ),
    ]
