# Generated by Django 6.0.6 on 2026-06-17 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0007_gallerypage_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptionSlidePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default='Best wishes for the year ahead!', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'caption slide page',
                'verbose_name_plural': 'caption slide pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaptionSlideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='caption_slides/')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='decks.captionslidepage')),
            ],
            options={
                'verbose_name': 'caption slide image',
                'verbose_name_plural': 'caption slide images',
                'ordering': ['order'],
            },
        ),
    ]
