# Generated by Django 6.0.6 on 2026-06-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0008_captionslidepage_captionslideimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='captionslideimage',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='captionslideimage',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='captionslidepage',
            name='title',
            field=models.CharField(default='New Joiners', max_length=200),
        ),
    ]
