# Generated by Django 6.0.6 on 2026-06-18 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0009_captionslideimage_designation_captionslideimage_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewJoinersPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Joiners', max_length=200)),
                ('caption', models.CharField(default='Welcome aboard! Glad to have you with us!', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'new joiners page',
                'verbose_name_plural': 'new joiners pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='captionslideimage',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='captionslideimage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='captionslidepage',
            name='title',
        ),
        migrations.CreateModel(
            name='NewJoiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='new_joiners/')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joiners', to='decks.newjoinerspage')),
            ],
            options={
                'verbose_name': 'new joiner',
                'verbose_name_plural': 'new joiners',
                'ordering': ['order'],
            },
        ),
    ]
