# Generated by Django 6.0.6 on 2026-06-18 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0011_promotionspage_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='KudosMomentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Kudos Moments', max_length=200)),
                ('display_type', models.CharField(choices=[('cards_only', 'Cards only'), ('image_with_cards', 'Image with cards')], default='image_with_cards', max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='kudos_moments/')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('designation', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'kudos moment page',
                'verbose_name_plural': 'kudos moment pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KudosMomentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='decks.kudosmomentpage')),
            ],
            options={
                'verbose_name': 'kudos moment card',
                'verbose_name_plural': 'kudos moment cards',
                'ordering': ['order'],
            },
        ),
    ]
