# Generated by Django 6.0.6 on 2026-06-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0012_kudosmomentpage_kudosmomentcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialAppreciationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Special Appreciation', max_length=200)),
                ('image', models.ImageField(upload_to='special_appreciations/')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'special appreciation page',
                'verbose_name_plural': 'special appreciation pages',
                'ordering': ['-created_at'],
            },
        ),
    ]
