# Generated by Django 6.0.6 on 2026-06-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0013_specialappreciationpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialappreciationpage',
            name='image_height',
            field=models.PositiveSmallIntegerField(default=430, help_text='Maximum image height in pixels.'),
        ),
        migrations.AddField(
            model_name='specialappreciationpage',
            name='image_width',
            field=models.PositiveSmallIntegerField(default=330, help_text='Image/card width in pixels.'),
        ),
    ]
