# Generated by Django 6.0.6 on 2026-06-18 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0014_specialappreciationpage_image_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialappreciationpage',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='specialappreciationpage',
            name='image_width',
        ),
    ]
