# Generated by Django 6.0.6 on 2026-06-18 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0015_remove_specialappreciationpage_image_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KudosBulletMomentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Kudos Moments', max_length=200)),
                ('display_type', models.CharField(choices=[('cards_only', 'Cards only'), ('image_with_cards', 'Image with cards')], default='image_with_cards', max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='kudos_bullet_moments/')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('designation', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'kudos bullet moment page',
                'verbose_name_plural': 'kudos bullet moment pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KudosBulletMomentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('metric', 'Metric'), ('text', 'Text'), ('bullets', 'Bullets')], default='metric', max_length=20)),
                ('value', models.CharField(blank=True, default='', max_length=60)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('content', models.TextField(blank=True, default='', help_text='For bullets, enter one item per line.')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='decks.kudosbulletmomentpage')),
            ],
            options={
                'verbose_name': 'kudos bullet moment card',
                'verbose_name_plural': 'kudos bullet moment cards',
                'ordering': ['order'],
            },
        ),
    ]
