# Generated by Django 6.0.6 on 2026-06-18 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0016_kudosbulletmomentpage_kudosbulletmomentcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerOpportunityPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Career Opportunities', max_length=200)),
                ('content', models.TextField(default='Expanding our talent horizon, building high-impact teams, and creating space for the next generation of leaders.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'career opportunity page',
                'verbose_name_plural': 'career opportunity pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerOpportunityJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, default='')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='decks.careeropportunitypage')),
            ],
            options={
                'verbose_name': 'career opportunity job',
                'verbose_name_plural': 'career opportunity jobs',
                'ordering': ['order'],
            },
        ),
    ]
