# Generated by Django 6.0.6 on 2026-06-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0019_slideorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstpage',
            name='image',
        ),
        migrations.AlterField(
            model_name='hiddenslide',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='slideorder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
