from django.urls import path

from . import views

urlpatterns = [
    path("delete/<slug:page_type>/<int:pk>/", views.delete_page_item, name="delete_page_item"),
    path("delete-item/<slug:item_type>/<int:pk>/", views.delete_child_item, name="delete_child_item"),
    path("slides/", views.all_slides_view, name="all_slides"),
    path("slides/export-powerpoint/", views.export_slides_powerpoint, name="export_slides_powerpoint"),
    path("slides/order/", views.save_slide_order, name="save_slide_order"),
    path("slides/remove/", views.remove_slide_from_view, name="remove_slide_from_view"),
    path("slides/reset/", views.reset_removed_slides, name="reset_removed_slides"),
    path("first_page_list/", views.first_page_list, name="first_page_list"),
    path("first_page_list/<int:pk>/", views.first_page_list, name="first_page_detail"),
    path("next-page/", views.next_page_dashboard, name="next_page_dashboard"),
    path("next-page-view/", views.next_page_view, name="next_page_view"),
    path("next-page-view/<int:pk>/", views.next_page_view, name="next_page_view_detail"),
    path("agency-page/", views.agency_page_dashboard, name="agency_page_dashboard"),
    path("agency-page-view/", views.agency_page_view, name="agency_page_view"),
    path("agency-page-view/<int:pk>/", views.agency_page_view, name="agency_page_view_detail"),
    path("bullet-page/", views.bullet_page_dashboard, name="bullet_page_dashboard"),
    path("bullet-page-view/", views.bullet_page_view, name="bullet_page_view"),
    path("bullet-page-view/<int:pk>/", views.bullet_page_view, name="bullet_page_view_detail"),
    path("client-date-page/", views.client_date_page_dashboard, name="client_date_page_dashboard"),
    path("client-date-page-view/", views.client_date_page_view, name="client_date_page_view"),
    path("client-date-page-view/<int:pk>/", views.client_date_page_view, name="client_date_page_view_detail"),
    path("client-says-page/", views.client_says_page_dashboard, name="client_says_page_dashboard"),
    path("client-says-page-view/", views.client_says_page_view, name="client_says_page_view"),
    path("client-says-page-view/<int:pk>/", views.client_says_page_view, name="client_says_page_view_detail"),
    path("gallery-page/", views.gallery_page_dashboard, name="gallery_page_dashboard"),
    path("gallery-page-view/", views.gallery_page_view, name="gallery_page_view"),
    path("gallery-page-view/<int:pk>/", views.gallery_page_view, name="gallery_page_view_detail"),
    path("new-joiners/", views.new_joiners_dashboard, name="new_joiners_dashboard"),
    path("new-joiners-view/", views.new_joiners_view, name="new_joiners_view"),
    path("new-joiners-view/<int:pk>/", views.new_joiners_view, name="new_joiners_view_detail"),
    path("promotions/", views.promotions_dashboard, name="promotions_dashboard"),
    path("promotions-view/", views.promotions_view, name="promotions_view"),
    path("promotions-view/<int:pk>/", views.promotions_view, name="promotions_view_detail"),
    path("kudos-moments/", views.kudos_moments_dashboard, name="kudos_moments_dashboard"),
    path("kudos-moments-view/", views.kudos_moments_view, name="kudos_moments_view"),
    path("kudos-moments-view/<int:pk>/", views.kudos_moments_view, name="kudos_moments_view_detail"),
    path("kudos-bullet-moments/", views.kudos_bullet_moments_dashboard, name="kudos_bullet_moments_dashboard"),
    path("kudos-bullet-moments-view/", views.kudos_bullet_moments_view, name="kudos_bullet_moments_view"),
    path("kudos-bullet-moments-view/<int:pk>/", views.kudos_bullet_moments_view, name="kudos_bullet_moments_view_detail"),
    path("special-appreciation/", views.special_appreciation_dashboard, name="special_appreciation_dashboard"),
    path("special-appreciation-view/", views.special_appreciation_view, name="special_appreciation_view"),
    path("special-appreciation-view/<int:pk>/", views.special_appreciation_view, name="special_appreciation_view_detail"),
    path("career-opportunities/", views.career_opportunities_dashboard, name="career_opportunities_dashboard"),
    path("career-opportunities-view/", views.career_opportunities_view, name="career_opportunities_view"),
    path("career-opportunities-view/<int:pk>/", views.career_opportunities_view, name="career_opportunities_view_detail"),
    path("caption-slide-page/", views.caption_slide_page_dashboard, name="caption_slide_page_dashboard"),
    path("caption-slide-page-view/", views.caption_slide_page_view, name="caption_slide_page_view"),
    path("caption-slide-page-view/<int:pk>/", views.caption_slide_page_view, name="caption_slide_page_view_detail"),
    path("", views.dashboard, name="dashboard"),
]
